$(document).ready(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();


$("#instrumentone").click(function()
{
$(instrument1).toggle(500);
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});
   
        
$("#instrumenttwo").click(function()
{		
$(instrument1).hide();
$(instrument2).toggle(500);
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumentthree").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).toggle(500);
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumentfour").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).toggle(500);
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumentfive").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).toggle(500);
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumentsix").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).toggle(500);
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumentseven").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).toggle(500);
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumenteight").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).toggle(500);
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumentnine").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).toggle(500);
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumentten").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).toggle(500);
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumenteleven").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).toggle(500);
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumenttwelve").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).toggle(500);
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumentthirteen").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).toggle(500);
$(instrument14).hide();
$(instrument15).hide();
});

$("#instrumentfourteen").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).toggle(500);
$(instrument15).hide();
});

$("#instrumentfifteen").click(function()
{
$(instrument1).hide();
$(instrument2).hide();
$(instrument3).hide();
$(instrument4).hide();
$(instrument5).hide();
$(instrument6).hide();
$(instrument7).hide();
$(instrument8).hide();
$(instrument9).hide();
$(instrument10).hide();
$(instrument11).hide();
$(instrument12).hide();
$(instrument13).hide();
$(instrument14).hide();
$(instrument15).toggle(500);
});

});