$(document).ready(function()
{
	$(tab1_data).hide();
	$(tab2_data).hide();
	$(tab3_data).hide();
	$(tab4_data).hide();
	$(tab5_data).hide();
	$(tab6_data).hide();
	$(tab7_data).hide();
	$(tab8_data).hide();
	$(tab9_data).hide();
	$(tab10_data).hide();
	
	$(map1_data).hide();
	$(map2_data).hide();
	$(map3_data).hide();
	$(map4_data).hide();
	$(map5_data).hide();
	$(map6_data).hide();
	$(map7_data).hide();
	$(map8_data).hide();
	$(map9_data).hide();
	$(map10_data).hide();
	
	$("#map1").click(function()
	{
		$(map1_data).toggle();
	});
	$("#map2").click(function()
	{
		$(map2_data).toggle();
	});
	$("#map3").click(function()
	{
		$(map3_data).toggle();
	});
	$("#map4").click(function()
	{
		$(map4_data).toggle();
	});
	$("#map5").click(function()
	{
		$(map5_data).toggle();
	});
	$("#map6").click(function()
	{
		$(map6_data).toggle();
	});
	$("#map7").click(function()
	{
		$(map7_data).toggle();
	});
	$("#map8").click(function()
	{
		$(map8_data).toggle();
	});
	$("#map9").click(function()
	{
		$(map9_data).toggle();
	});
	$("#map10").click(function()
	{
		$(map10_data).toggle();
	});
	
	$("#tab1").click(function()
	{
		$(tab1_data).toggle(500);
			$(tab1a_data).hide();
			$(tab1b_data).hide();
			$(tab1c_data).hide();
			$(tab1d_data).hide();
			$(tab1e_data).hide();
			$(tab1f_data).hide();
			$(tab1g_data).hide();
			$(tab1h_data).hide();
			$(tab1i_data).hide();
			$(tab1j_data).hide();
		$("#tab1a").click(function()
		{
			$(tab1a_data).toggle(500);
		});
		$("#tab1b").click(function()
		{
			$(tab1b_data).toggle(500);
		});
		$("#tab1c").click(function()
		{
			$(tab1c_data).toggle(500);
		});
		$("#tab1d").click(function()
		{
			$(tab1d_data).toggle(500);
		});
		$("#tab1e").click(function()
		{
			$(tab1e_data).toggle(500);
		});
		$("#tab1f").click(function()
		{
			$(tab1f_data).toggle(500);
		});
		$("#tab1g").click(function()
		{
			$(tab1g_data).toggle(500);
		});
		$("#tab1h").click(function()
		{
			$(tab1h_data).toggle(500);
		});
		$("#tab1i").click(function()
		{
			$(tab1i_data).toggle(500);
		});
		$("#tab1j").click(function()
		{
			$(tab1j_data).toggle(500);
		});
	});
	
	$("#tab2").click(function()
	{
		$(tab2_data).toggle(500);
			$(tab2a_data).hide();
			$(tab2b_data).hide();
			$(tab2c_data).hide();
			$(tab2d_data).hide();
			$(tab2e_data).hide();
			$(tab2f_data).hide();
			$(tab2g_data).hide();
			$(tab2h_data).hide();
			$(tab2i_data).hide();
			$(tab2j_data).hide();
		$("#tab2a").click(function()
		{
			$(tab2a_data).toggle(500);
		});
		$("#tab2b").click(function()
		{
			$(tab2b_data).toggle(500);
		});
		$("#tab2c").click(function()
		{
			$(tab2c_data).toggle(500);
		});
		$("#tab2d").click(function()
		{
			$(tab2d_data).toggle(500);
		});
		$("#tab2e").click(function()
		{
			$(tab2e_data).toggle(500);
		});
		$("#tab2f").click(function()
		{
			$(tab2f_data).toggle(500);
		});
		$("#tab2g").click(function()
		{
			$(tab2g_data).toggle(500);
		});
		$("#tab2h").click(function()
		{
			$(tab2h_data).toggle(500);
		});
		$("#tab2i").click(function()
		{
			$(tab2i_data).toggle(500);
		});
		$("#tab2j").click(function()
		{
			$(tab2j_data).toggle(500);
		});
	});
	$("#tab3").click(function()
	{
		$(tab3_data).toggle(500);
			$(tab3a_data).hide();
			$(tab3b_data).hide();
			$(tab3c_data).hide();
			$(tab3d_data).hide();
			$(tab3e_data).hide();
			$(tab3f_data).hide();
			$(tab3g_data).hide();
			$(tab3h_data).hide();
			$(tab3i_data).hide();
		$("#tab3a").click(function()
		{
			$(tab3a_data).toggle(500);
		});
		$("#tab3b").click(function()
		{
			$(tab3b_data).toggle(500);
		});
		$("#tab3c").click(function()
		{
			$(tab3c_data).toggle(500);
		});
		$("#tab3d").click(function()
		{
			$(tab3d_data).toggle(500);
		});
		$("#tab3e").click(function()
		{
			$(tab3e_data).toggle(500);
		});
		$("#tab3f").click(function()
		{
			$(tab3f_data).toggle(500);
		});
		$("#tab3g").click(function()
		{
			$(tab2g_data).toggle(500);
		});
		$("#tab3h").click(function()
		{
			$(tab3h_data).toggle(500);
		});
		$("#tab3i").click(function()
		{
			$(tab3i_data).toggle(500);
		});
	});
	
	$("#tab4").click(function()
	{
		$(tab4_data).toggle(500);
			$(tab4a_data).hide();
			$(tab4b_data).hide();
			$(tab4c_data).hide();
			$(tab4d_data).hide();
			$(tab4e_data).hide();
			$(tab4f_data).hide();
			$(tab4g_data).hide();
			$(tab4h_data).hide();
			$(tab4i_data).hide();
			$(tab4j_data).hide();
			$(tab4k_data).hide();
			$(tab4l_data).hide();
			$(tab4m_data).hide();
		$("#tab4a").click(function()
		{
			$(tab4a_data).toggle(500);
		});
		$("#tab4b").click(function()
		{
			$(tab4b_data).toggle(500);
		});
		$("#tab4c").click(function()
		{
			$(tab4c_data).toggle(500);
		});
		$("#tab4d").click(function()
		{
			$(tab4d_data).toggle(500);
		});
		$("#tab4e").click(function()
		{
			$(tab4e_data).toggle(500);
		});
		$("#tab4f").click(function()
		{
			$(tab4f_data).toggle(500);
		});
		$("#tab4g").click(function()
		{
			$(tab4g_data).toggle(500);
		});
		$("#tab4h").click(function()
		{
			$(tab4h_data).toggle(500);
		});
		$("#tab4i").click(function()
		{
			$(tab4i_data).toggle(500);
		});
		$("#tab4j").click(function()
		{
			$(tab4j_data).toggle(500);
		});
		$("#tab4k").click(function()
		{
			$(tab4k_data).toggle(500);
		});
		$("#tab4l").click(function()
		{
			$(tab4l_data).toggle(500);
		});
		$("#tab4m").click(function()
		{
			$(tab4m_data).toggle(500);
		});
	});
	
	$("#tab5").click(function()
	{
		$(tab5_data).toggle(500);
			$(tab5a_data).hide();
			$(tab5b_data).hide();
			$(tab5c_data).hide();
			$(tab5d_data).hide();
			$(tab5e_data).hide();
			$(tab5f_data).hide();
			$(tab5g_data).hide();
			$(tab5h_data).hide();
			$(tab5i_data).hide();
			$(tab5j_data).hide();
			$(tab5k_data).hide();
			$(tab5l_data).hide();
			$(tab5m_data).hide();
			$(tab5n_data).hide();
			$(tab5o_data).hide();
			$(tab5p_data).hide();
			$(tab5q_data).hide();
			$(tab5r_data).hide();
		$("#tab5a").click(function()
		{
			$(tab5a_data).toggle(500);
		});
		$("#tab5b").click(function()
		{
			$(tab5b_data).toggle(500);
		});
		$("#tab5c").click(function()
		{
			$(tab5c_data).toggle(500);
		});
		$("#tab5d").click(function()
		{
			$(tab5d_data).toggle(500);
		});
		$("#tab5e").click(function()
		{
			$(tab5e_data).toggle(500);
		});
		$("#tab5f").click(function()
		{
			$(tab5f_data).toggle(500);
		});
		$("#tab5g").click(function()
		{
			$(tab5g_data).toggle(500);
		});
		$("#tab5h").click(function()
		{
			$(tab5h_data).toggle(500);
		});
		$("#tab5i").click(function()
		{
			$(tab5i_data).toggle(500);
		});
		$("#tab5j").click(function()
		{
			$(tab5j_data).toggle(500);
		});
		$("#tab5k").click(function()
		{
			$(tab5k_data).toggle(500);
		});
		$("#tab5l").click(function()
		{
			$(tab5l_data).toggle(500);
		});
		$("#tab5m").click(function()
		{
			$(tab5m_data).toggle(500);
		});
		$("#tab5n").click(function()
		{
			$(tab5n_data).toggle(500);
		});
		$("#tab5o").click(function()
		{
			$(tab5o_data).toggle(500);
		});
		$("#tab5p").click(function()
		{
			$(tab5p_data).toggle(500);
		});
		$("#tab5q").click(function()
		{
			$(tab5q_data).toggle(500);
		});
		$("#tab5r").click(function()
		{
			$(tab5r_data).toggle(500);
		});
	});
	
	$("#tab6").click(function()
	{
		$(tab6_data).toggle(500);
			$(tab6a_data).hide();
			$(tab6b_data).hide();
			$(tab6c_data).hide();
			$(tab6d_data).hide();
			$(tab6e_data).hide();
			$(tab6f_data).hide();
			$(tab6g_data).hide();
			$(tab6h_data).hide();
			$(tab6i_data).hide();
			$(tab6j_data).hide();
			$(tab6k_data).hide();
			$(tab6l_data).hide();
			$(tab6m_data).hide();
			$(tab6n_data).hide();
		$("#tab6a").click(function()
		{
			$(tab6a_data).toggle(500);
		});
		$("#tab6b").click(function()
		{
			$(tab6b_data).toggle(500);
		});
		$("#tab6c").click(function()
		{
			$(tab6c_data).toggle(500);
		});
		$("#tab6d").click(function()
		{
			$(tab6d_data).toggle(500);
		});
		$("#tab6e").click(function()
		{
			$(tab6e_data).toggle(500);
		});
		$("#tab6f").click(function()
		{
			$(tab6f_data).toggle(500);
		});
		$("#tab6g").click(function()
		{
			$(tab6g_data).toggle(500);
		});
		$("#tab6h").click(function()
		{
			$(tab6h_data).toggle(500);
		});
		$("#tab6i").click(function()
		{
			$(tab6i_data).toggle(500);
		});
		$("#tab6j").click(function()
		{
			$(tab6j_data).toggle(500);
		});
		$("#tab6k").click(function()
		{
			$(tab6k_data).toggle(500);
		});
		$("#tab6l").click(function()
		{
			$(tab6l_data).toggle(500);
		});
		$("#tab6m").click(function()
		{
			$(tab6m_data).toggle(500);
		});
		$("#tab6n").click(function()
		{
			$(tab6n_data).toggle(500);
		});
	});
	
	$("#tab7").click(function()
	{
		$(tab7_data).toggle(500);
			$(tab7a_data).hide();
			$(tab7b_data).hide();
			$(tab7c_data).hide();
			$(tab7d_data).hide();
			$(tab7e_data).hide();
			$(tab7f_data).hide();
			$(tab7g_data).hide();
			$(tab7h_data).hide();
			$(tab7i_data).hide();
		$("#tab7a").click(function()
		{
			$(tab7a_data).toggle(500);
		});
		$("#tab7b").click(function()
		{
			$(tab7b_data).toggle(500);
		});
		$("#tab7c").click(function()
		{
			$(tab7c_data).toggle(500);
		});
		$("#tab7d").click(function()
		{
			$(tab7d_data).toggle(500);
		});
		$("#tab7e").click(function()
		{
			$(tab7e_data).toggle(500);
		});
		$("#tab7f").click(function()
		{
			$(tab7f_data).toggle(500);
		});
		$("#tab7g").click(function()
		{
			$(tab7g_data).toggle(500);
		});
		$("#tab7h").click(function()
		{
			$(tab7h_data).toggle(500);
		});
		$("#tab7i").click(function()
		{
			$(tab7i_data).toggle(500);
		});
	});
	
	$("#tab8").click(function()
	{
		$(tab8_data).toggle(500);
			$(tab8a_data).hide();
			$(tab8b_data).hide();
			$(tab8c_data).hide();
			$(tab8d_data).hide();
			$(tab8e_data).hide();
			$(tab8f_data).hide();
			$(tab8g_data).hide();
		$("#tab8a").click(function()
		{
			$(tab8a_data).toggle(500);
		});
		$("#tab8b").click(function()
		{
			$(tab8b_data).toggle(500);
		});
		$("#tab8c").click(function()
		{
			$(tab8c_data).toggle(500);
		});
		$("#tab8d").click(function()
		{
			$(tab8d_data).toggle(500);
		});
		$("#tab8e").click(function()
		{
			$(tab8e_data).toggle(500);
		});
		$("#tab8f").click(function()
		{
			$(tab8f_data).toggle(500);
		});
		$("#tab8g").click(function()
		{
			$(tab8g_data).toggle(500);
		});
	});
	
	$("#tab9").click(function()
	{
		$(tab9_data).toggle(500);
			$(tab9a_data).hide();
			$(tab9b_data).hide();
			$(tab9c_data).hide();
			$(tab9d_data).hide();
			$(tab9e_data).hide();
			$(tab9f_data).hide();
			$(tab9g_data).hide();
			$(tab9h_data).hide();
		$("#tab9a").click(function()
		{
			$(tab9a_data).toggle(500);
		});
		$("#tab9b").click(function()
		{
			$(tab9b_data).toggle(500);
		});
		$("#tab9c").click(function()
		{
			$(tab9c_data).toggle(500);
		});
		$("#tab9d").click(function()
		{
			$(tab9d_data).toggle(500);
		});
		$("#tab9e").click(function()
		{
			$(tab9e_data).toggle(500);
		});
		$("#tab9f").click(function()
		{
			$(tab9f_data).toggle(500);
		});
		$("#tab9g").click(function()
		{
			$(tab9g_data).toggle(500);
		});
		$("#tab9h").click(function()
		{
			$(tab9h_data).toggle(500);
		});
	});
	
	$("#tab10").click(function()
	{
		$(tab10_data).toggle(500);
			$(tab10a_data).hide();
			$(tab10b_data).hide();
			$(tab10c_data).hide();
			$(tab10d_data).hide();
			$(tab10e_data).hide();
			$(tab10f_data).hide();
			$(tab10g_data).hide();
			$(tab10h_data).hide();
		$("#tab10a").click(function()
		{
			$(tab10a_data).toggle(500);
		});
		$("#tab10b").click(function()
		{
			$(tab10b_data).toggle(500);
		});
		$("#tab10c").click(function()
		{
			$(tab10c_data).toggle(500);
		});
		$("#tab10d").click(function()
		{
			$(tab10d_data).toggle(500);
		});
		$("#tab10e").click(function()
		{
			$(tab10e_data).toggle(500);
		});
		$("#tab10f").click(function()
		{
			$(tab10f_data).toggle(500);
		});
		$("#tab10g").click(function()
		{
			$(tab10g_data).toggle(500);
		});
		$("#tab10h").click(function()
		{
			$(tab10h_data).toggle(500);
		});
	});
});