$(document).ready(function()
{
	$(map1_data).hide();
		$(tab1a_map_data).hide();
		$(tab1b_map_data).hide();
		$(tab1c_map_data).hide();
		$(tab1d_map_data).hide();
		$(tab1e_map_data).hide();
		$(tab1f_map_data).hide();
		$(tab1g_map_data).hide();
		$(tab1h_map_data).hide();
		$(tab1i_map_data).hide();
		$(tab1j_map_data).hide();
		$(tab1k_map_data).hide();
		$(tab1l_map_data).hide();
		$(tab1m_map_data).hide();
		$(tab1n_map_data).hide();
		$(tab1o_map_data).hide();
		$(tab1p_map_data).hide();
		$(tab1q_map_data).hide();
		$(tab1r_map_data).hide();
		$(tab1s_map_data).hide();
	$(map2_data).hide();
	$(map3_data).hide();
	$(map4_data).hide();
	$(map5_data).hide();
	$(map6_data).hide();
	$(map7_data).hide();
	$(map8_data).hide();
	$(map9_data).hide();
	$(map10_data).hide();
	$(map11_data).hide();
	$(map12_data).hide();
	$(map13_data).hide();
	$(map14_data).hide();
	$(map15_data).hide();
	$(map16_data).hide();
	$(map17_data).hide();
	$(map18_data).hide();
	$(map19_data).hide();
	$(map20_data).hide();
	$(map21_data).hide();
	$(map22_data).hide();
		$(tab22a_map_data).hide();
		$(tab22b_map_data).hide();
		$(tab22c_map_data).hide();
		$(tab22d_map_data).hide();
		$(tab22e_map_data).hide();
		$(tab22f_map_data).hide();
		$(tab22g_map_data).hide();
		$(tab22h_map_data).hide();
		$(tab22i_map_data).hide();
		$(tab22j_map_data).hide();
		$(tab22k_map_data).hide();
		$(tab22l_map_data).hide();
		$(tab22m_map_data).hide();
		
	$(tab1_data).hide();
		$(tab1a_data).hide();
		$(tab1b_data).hide();
		$(tab1c_data).hide();
		$(tab1d_data).hide();
		$(tab1e_data).hide();
		$(tab1f_data).hide();
		$(tab1g_data).hide();
		$(tab1h_data).hide();
		$(tab1i_data).hide();
		$(tab1j_data).hide();
		$(tab1k_data).hide();
		$(tab1l_data).hide();
		$(tab1m_data).hide();
		$(tab1n_data).hide();
		$(tab1o_data).hide();
		$(tab1p_data).hide();
		$(tab1q_data).hide();
		$(tab1r_data).hide();
		$(tab1s_data).hide();
	$(tab2_data).hide();
	$(tab3_data).hide();
	$(tab4_data).hide();
	$(tab5_data).hide();
	$(tab6_data).hide();
	$(tab7_data).hide();
	$(tab8_data).hide();
	$(tab9_data).hide();
	$(tab10_data).hide();
	$(tab11_data).hide();
	$(tab12_data).hide();
	$(tab13_data).hide();
	$(tab14_data).hide();
	$(tab15_data).hide();
	$(tab16_data).hide();
	$(tab17_data).hide();
	$(tab18_data).hide();
	$(tab19_data).hide();
	$(tab20_data).hide();
	$(tab21_data).hide();
	$(tab22_data).hide();
		$(tab22a_data).hide();
		$(tab22b_data).hide();
		$(tab22c_data).hide();
		$(tab22d_data).hide();
		$(tab22e_data).hide();
		$(tab22f_data).hide();
		$(tab22g_data).hide();
		$(tab22h_data).hide();
		$(tab22i_data).hide();
		$(tab22j_data).hide();
		$(tab22k_data).hide();
		$(tab22l_data).hide();
		$(tab22m_data).hide();
		
	$("#map1").click(function()
	{
		$(map1_data).toggle();
	});
		$("#tab1a_map").click(function()
		{
			$(tab1a_map_data).toggle();
		});
		$("#tab1b_map").click(function()
		{
			$(tab1b_map_data).toggle();
		});
		$("#tab1c_map").click(function()
		{
			$(tab1c_map_data).toggle();
		});
		$("#tab1d_map").click(function()
		{
			$(tab1d_map_data).toggle();
		});
		$("#tab1e_map").click(function()
		{
			$(tab1e_map_data).toggle();
		});
		$("#tab1f_map").click(function()
		{
			$(tab1f_map_data).toggle();
		});
		$("#tab1g_map").click(function()
		{
			$(tab1g_map_data).toggle();
		});
		$("#tab1h_map").click(function()
		{
			$(tab1h_map_data).toggle();
		});
		$("#tab1i_map").click(function()
		{
			$(tab1i_map_data).toggle();
		});
		$("#tab1j_map").click(function()
		{
			$(tab1j_map_data).toggle();
		});
		$("#tab1k_map").click(function()
		{
			$(tab1k_map_data).toggle();
		});
		$("#tab1l_map").click(function()
		{
			$(tab1l_map_data).toggle();
		});
		$("#tab1m_map").click(function()
		{
			$(tab1m_map_data).toggle();
		});
		$("#tab1n_map").click(function()
		{
			$(tab1n_map_data).toggle();
		});
		$("#tab1o_map").click(function()
		{
			$(tab1o_map_data).toggle();
		});
		$("#tab1p_map").click(function()
		{
			$(tab1p_map_data).toggle();
		});
		$("#tab1q_map").click(function()
		{
			$(tab1q_map_data).toggle();
		});
		$("#tab1r_map").click(function()
		{
			$(tab1r_map_data).toggle();
		});
		$("#tab1s_map").click(function()
		{
			$(tab1s_map_data).toggle();
		});
		
	$("#map22").click(function()
	{
		$(map22_data).toggle();
	});
		$("#tab22a_map").click(function()
		{
			$(tab22a_map_data).toggle();
		});
		$("#tab22b_map").click(function()
		{
			$(tab22b_map_data).toggle();
		});
		$("#tab22c_map").click(function()
		{
			$(tab22c_map_data).toggle();
		});
		$("#tab22d_map").click(function()
		{
			$(tab22d_map_data).toggle();
		});
		$("#tab22e_map").click(function()
		{
			$(tab22e_map_data).toggle();
		});
		$("#tab22f_map").click(function()
		{
			$(tab22f_map_data).toggle();
		});
		$("#tab22g_map").click(function()
		{
			$(tab22g_map_data).toggle();
		});
		$("#tab22h_map").click(function()
		{
			$(tab22h_map_data).toggle();
		});
		$("#tab22i_map").click(function()
		{
			$(tab22i_map_data).toggle();
		});
		$("#tab22j_map").click(function()
		{
			$(tab22j_map_data).toggle();
		});
		$("#tab22k_map").click(function()
		{
			$(tab22k_map_data).toggle();
		});
		$("#tab22l_map").click(function()
		{
			$(tab22l_map_data).toggle();
		});
		$("#tab22m_map").click(function()
		{
			$(tab22m_map_data).toggle();
		});
		
	$("#tab1").click(function()
	{
		$(tab1_data).toggle(500);
	});
		$("#tab1a").click(function()
			{
				$(tab1a_data).toggle(500);
			});
			$("#tab1b").click(function()
			{
				$(tab1b_data).toggle(500);
			});
			$("#tab1c").click(function()
			{
				$(tab1c_data).toggle(500);
			});
			$("#tab1d").click(function()
			{
				$(tab1d_data).toggle(500);
			});
			$("#tab1e").click(function()
			{
				$(tab1e_data).toggle(500);
			});
			$("#tab1f").click(function()
			{
				$(tab1f_data).toggle(500);
			});
			$("#tab1g").click(function()
			{
				$(tab1g_data).toggle(500);
			});
			$("#tab1h").click(function()
			{
				$(tab1h_data).toggle(500);
			});
			$("#tab1i").click(function()
			{
				$(tab1i_data).toggle(500);
			});
			$("#tab1j").click(function()
			{
				$(tab1j_data).toggle(500);
			});
			$("#tab1k").click(function()
			{
				$(tab1k_data).toggle(500);
			});
			$("#tab1l").click(function()
			{
				$(tab1l_data).toggle(500);
			});
			$("#tab1m").click(function()
			{
				$(tab1m_data).toggle(500);
			});
			$("#tab1n").click(function()
			{
				$(tab1n_data).toggle(500);
			});
			$("#tab1o").click(function()
			{
				$(tab1o_data).toggle(500);
			});
			$("#tab1p").click(function()
			{
				$(tab1p_data).toggle(500);
			});
			$("#tab1q").click(function()
			{
				$(tab1q_data).toggle(500);
			});
			$("#tab1r").click(function()
			{
				$(tab1r_data).toggle(500);
			});
			$("#tab1s").click(function()
			{
				$(tab1s_data).toggle(500);
			});
		
		$("#tab22").click(function()
	{
		$(tab22_data).toggle(500);
	});
		$("#tab22a").click(function()
			{
				$(tab22a_data).toggle(500);
			});
			$("#tab22b").click(function()
			{
				$(tab22b_data).toggle(500);
			});
			$("#tab22c").click(function()
			{
				$(tab22c_data).toggle(500);
			});
			$("#tab22d").click(function()
			{
				$(tab22d_data).toggle(500);
			});
			$("#tab22e").click(function()
			{
				$(tab22e_data).toggle(500);
			});
			$("#tab22f").click(function()
			{
				$(tab22f_data).toggle(500);
			});
			$("#tab22g").click(function()
			{
				$(tab22g_data).toggle(500);
			});
			$("#tab22h").click(function()
			{
				$(tab22h_data).toggle(500);
			});
			$("#tab22i").click(function()
			{
				$(tab22i_data).toggle(500);
			});
			$("#tab22j").click(function()
			{
				$(tab22j_data).toggle(500);
			});
			$("#tab22k").click(function()
			{
				$(tab22k_data).toggle(500);
			});
			$("#tab22l").click(function()
			{
				$(tab22l_data).toggle(500);
			});
			$("#tab22m").click(function()
			{
				$(tab22m_data).toggle(500);
			});
			
		$("#tab_show_all").click(function()
		{
			$(map1_data).show();
				$(tab1a_map_data).show();
				$(tab1b_map_data).show();
				$(tab1c_map_data).show();
				$(tab1d_map_data).show();
				$(tab1e_map_data).show();
				$(tab1f_map_data).show();
				$(tab1g_map_data).show();
				$(tab1h_map_data).show();
				$(tab1i_map_data).show();
				$(tab1j_map_data).show();
				$(tab1k_map_data).show();
				$(tab1l_map_data).show();
				$(tab1m_map_data).show();
				$(tab1n_map_data).show();
				$(tab1o_map_data).show();
				$(tab1p_map_data).show();
				$(tab1q_map_data).show();
				$(tab1r_map_data).show();
				$(tab1s_map_data).show();
			$(map2_data).show();
			$(map3_data).show();
			$(map4_data).show();
			$(map5_data).show();
			$(map6_data).show();
			$(map7_data).show();
			$(map8_data).show();
			$(map9_data).show();
			$(map10_data).show();
			$(map11_data).show();
			$(map12_data).show();
			$(map13_data).show();
			$(map14_data).show();
			$(map15_data).show();
			$(map16_data).show();
			$(map17_data).show();
			$(map18_data).show();
			$(map19_data).show();
			$(map20_data).show();
			$(map21_data).show();
			$(map22_data).show();
				$(tab22a_map_data).show();
				$(tab22b_map_data).show();
				$(tab22c_map_data).show();
				$(tab22d_map_data).show();
				$(tab22e_map_data).show();
				$(tab22f_map_data).show();
				$(tab22g_map_data).show();
				$(tab22h_map_data).show();
				$(tab22i_map_data).show();
				$(tab22j_map_data).show();
				$(tab22k_map_data).show();
				$(tab22l_map_data).show();
				$(tab22m_map_data).show();
		
			$(tab1_data).show();
				$(tab1a_data).show();
				$(tab1b_data).show();
				$(tab1c_data).show();
				$(tab1d_data).show();
				$(tab1e_data).show();
				$(tab1f_data).show();
				$(tab1g_data).show();
				$(tab1h_data).show();
				$(tab1i_data).show();
				$(tab1j_data).show();
				$(tab1k_data).show();
				$(tab1l_data).show();
				$(tab1m_data).show();
				$(tab1n_data).show();
				$(tab1o_data).show();
				$(tab1p_data).show();
				$(tab1q_data).show();
				$(tab1r_data).show();
				$(tab1s_data).show();
			$(tab2_data).show();
			$(tab3_data).show();
			$(tab4_data).show();
			$(tab5_data).show();
			$(tab6_data).show();
			$(tab7_data).show();
			$(tab8_data).show();
			$(tab9_data).show();
			$(tab10_data).show();
			$(tab11_data).show();
			$(tab12_data).show();
			$(tab13_data).show();
			$(tab14_data).show();
			$(tab15_data).show();
			$(tab16_data).show();
			$(tab17_data).show();
			$(tab18_data).show();
			$(tab19_data).show();
			$(tab20_data).show();
			$(tab21_data).show();
			$(tab22_data).show();
				$(tab22a_data).show();
				$(tab22b_data).show();
				$(tab22c_data).show();
				$(tab22d_data).show();
				$(tab22e_data).show();
				$(tab22f_data).show();
				$(tab22g_data).show();
				$(tab22h_data).show();
				$(tab22i_data).show();
				$(tab22j_data).show();
				$(tab22k_data).show();
				$(tab22l_data).show();
				$(tab22m_data).show();
		});
		
		$("#tab_hide_all").click(function()
		{
			$(map1_data).hide();
				$(tab1a_map_data).hide();
				$(tab1b_map_data).hide();
				$(tab1c_map_data).hide();
				$(tab1d_map_data).hide();
				$(tab1e_map_data).hide();
				$(tab1f_map_data).hide();
				$(tab1g_map_data).hide();
				$(tab1h_map_data).hide();
				$(tab1i_map_data).hide();
				$(tab1j_map_data).hide();
				$(tab1k_map_data).hide();
				$(tab1l_map_data).hide();
				$(tab1m_map_data).hide();
				$(tab1n_map_data).hide();
				$(tab1o_map_data).hide();
				$(tab1p_map_data).hide();
				$(tab1q_map_data).hide();
				$(tab1r_map_data).hide();
				$(tab1s_map_data).hide();
			$(map2_data).hide();
			$(map3_data).hide();
			$(map4_data).hide();
			$(map5_data).hide();
			$(map6_data).hide();
			$(map7_data).hide();
			$(map8_data).hide();
			$(map9_data).hide();
			$(map10_data).hide();
			$(map11_data).hide();
			$(map12_data).hide();
			$(map13_data).hide();
			$(map14_data).hide();
			$(map15_data).hide();
			$(map16_data).hide();
			$(map17_data).hide();
			$(map18_data).hide();
			$(map19_data).hide();
			$(map20_data).hide();
			$(map21_data).hide();
			$(map22_data).hide();	
				$(tab22a_map_data).hide();
				$(tab22b_map_data).hide();
				$(tab22c_map_data).hide();
				$(tab22d_map_data).hide();
				$(tab22e_map_data).hide();
				$(tab22f_map_data).hide();
				$(tab22g_map_data).hide();
				$(tab22h_map_data).hide();
				$(tab22i_map_data).hide();
				$(tab22j_map_data).hide();
				$(tab22k_map_data).hide();
				$(tab22l_map_data).hide();
				$(tab22m_map_data).hide();
		
			$(tab1_data).hide();
				$(tab1a_data).hide();
				$(tab1b_data).hide();
				$(tab1c_data).hide();
				$(tab1d_data).hide();
				$(tab1e_data).hide();
				$(tab1f_data).hide();
				$(tab1g_data).hide();
				$(tab1h_data).hide();
				$(tab1i_data).hide();
				$(tab1j_data).hide();
				$(tab1k_data).hide();
				$(tab1l_data).hide();
				$(tab1m_data).hide();
				$(tab1n_data).hide();
				$(tab1o_data).hide();
				$(tab1p_data).hide();
				$(tab1q_data).hide();
				$(tab1r_data).hide();
				$(tab1s_data).hide();
			$(tab2_data).hide();
			$(tab3_data).hide();
			$(tab4_data).hide();
			$(tab5_data).hide();
			$(tab6_data).hide();
			$(tab7_data).hide();
			$(tab8_data).hide();
			$(tab9_data).hide();
			$(tab10_data).hide();
			$(tab11_data).hide();
			$(tab12_data).hide();
			$(tab13_data).hide();
			$(tab14_data).hide();
			$(tab15_data).hide();
			$(tab16_data).hide();
			$(tab17_data).hide();
			$(tab18_data).hide();
			$(tab19_data).hide();
			$(tab20_data).hide();
			$(tab21_data).hide();
			$(tab22_data).hide();
				$(tab22a_data).hide();
				$(tab22b_data).hide();
				$(tab22c_data).hide();
				$(tab22d_data).hide();
				$(tab22e_data).hide();
				$(tab22f_data).hide();
				$(tab22g_data).hide();
				$(tab22h_data).hide();
				$(tab22i_data).hide();
				$(tab22j_data).hide();
				$(tab22k_data).hide();
				$(tab22l_data).hide();
				$(tab22m_data).hide();
		});
		
});